package:
  name: menpofit
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo 0.7.*
    - scikit-learn >=0.17,<0.18
    - dlib 18.18
    - pandas 0.17.*

test:
  requires:
    - nose
    - mock

  imports:
    - menpofit

about:
  home: https://github.com/menpo/menpofit/
  license: BSD
